---
- name: Update apt sources
  apt:
    update_cache: yes
    cache_valid_time: 600
  register: apt_update
  until: apt_update|success
  retries: 5
  delay: 2
  tags:
    - calico-apt-packages

- name: Install calico packages
  apt:
    pkg: "{{ item }}"
    state: latest
  register: install_packages
  until: install_packages|success
  retries: 5
  delay: 2
  with_items: calico_apt_packages
  tags:
    - calico-apt-packages

- name: Install calico pip packages (venv)
  pip:
    name: "{{ item }}"
    state: present
    virtualenv: "{{ neutron_venv_bin | dirname }}"
    virtualenv_site_packages: "no"
    extra_args: "{{ pip_install_options|default('') }}"
  register: install_packages
  until: install_packages|success
  retries: 5
  delay: 2
  with_items: calico_pip_packages
  when:
    - neutron_venv_enabled | bool
  tags:
    - calico-install
    - calico-pip-packages

- name: Install calico pip packages (no venv)
  pip:
    name: "{{ item }}"
    state: present
    extra_args: "{{ pip_install_options|default('') }}"
  register: install_packages
  until: install_packages|success
  retries: 5
  delay: 2
  with_items: calico_pip_packages
  when:
    - not neutron_venv_enabled | bool
  tags:
    - calico-install
    - calico-pip-packages
