---
- name: Add calico apt-keys
  apt_key:
    id: "{{ item.hash_id }}"
    keyserver: "{{ item.keyserver | default(omit) }}"
    data: "{{ item.data | default(omit) }}"
    state: "present"
  with_items: calico_gpg_keys
  register: add_keys
  until: add_keys|success
  retries: 5
  delay: 2
  tags:
    - calico-apt-keys

- name: Add calico apt-keys using fallback keyserver
  apt_key:
    id: "{{ item.hash_id }}"
    keyserver: "{{ item.fallback_keyserver }}"
    state: "present"
  register: add_keys_fallback
  until: add_keys_fallback|success
  retries: 5
  delay: 2
  with_items: calico_gpg_keys
  when: add_keys|failed and item.fallback_keyserver is defined
  tags:
    - calico-apt-keys

- name: Drop calico repo pin
  template:
    src: "projectcalico_pin.pref.j2"
    dest: "/etc/apt/preferences.d/projectcalico_pin.pref"
    owner: "root"
    group: "root"
    mode: "0644"
  tags:
    - calico-repo-pin

- name: Add calico repo(s)
  apt_repository:
    repo: "{{ calico_apt_repo.repo }}"
    state: "{{ calico_apt_repo.state }}"
  register: add_repos
  until: add_repos|success
  retries: 5
  delay: 2
  tags:
    - calico-repos
