---
- name: Reload init scripts
  shell: initctl reload-configuration

- name: Restart calico felix
  service:
   name: "calico-felix"
   state: restarted

- name: Restart libvirt-bin
  service:
    name: "libvirt-bin"
    state: "restarted"
    pattern: "libvirt-bin"
