---
- name: Reload init scripts
  shell: initctl reload-configuration

- name: Restart calico-felix
  service:
   name: "calico-felix"
   state: restarted

- name: Restart calico-dhcp-agent
  service:
   name: "calico-dhcp-agent"
   state: restarted

- name: Restart libvirt-bin
  service:
    name: "libvirt-bin"
    state: "restarted"
    pattern: "libvirt-bin"
